version checked in local

diff --git a/jenkins/root-cvmfs-release b/jenkins/root-cvmfs-release
--- a/jenkins/root-cvmfs-release
+++ b/jenkins/root-cvmfs-release
@@ -1,5 +1,4 @@
-#!/usr/bin/env bash
-set -e -x
+#!/usr/bin/env bash 
 
 # afs_release.sh
 # 
@@ -10,7 +9,8 @@ set -e -x
 
 # Let's create the directory first in CVMFS
 
-basedir=/cvmfs/sft.cern.ch/lcg/app/releases/ROOT/${ROOTVERSION} 
+basedir=/cvmfs/sft.cern.ch/lcg/app/releases/ROOT 
+config=`echo ${Configuration} | tr "," " " | tr -d '"'`
 
 sudo -i -u cvsft<<EOF
 
@@ -21,62 +21,61 @@ echo "Transaction is already open. Exiting ..."
 exit 1                                                                                                                                                                                                                                    
 fi
 
-# Let's make the directory for new ROOT version first:
-echo "ROOT VERSION: $ROOTVERSION"
-echo "Value of the basedir: $basedir"
-mkdir -p $basedir
 
 if [ ! -d $basedir ]; then
-  echo 1>&2 "The directory $basedir doesn't exist!" >&2
-  exit 127
+    echo 1>&2 "The directory $basedir doesn't exist!" >&2
+    exit 127
 fi
 
 mkdir -p $basedir/${ROOTVERSION}/src
-tarfile="root_v${ROOTVERSION}.source.tar.gz"
-wget "https://root.cern.ch/download/${tarfile}" >null 2>&1
-if [ -f ${tarfile} ]; then
-   tar -zxvf ${tarfile} -C $basedir/${ROOTVERSION}/src
-   rm ${tarfile}
+tarfile=root_v${ROOTVERSION}.source.tar.gz
+wget https://root.cern.ch/download/\$tarfile
+if [ -f \$tarfile ]; then
+    tar -zxvf \$tarfile -C $basedir/${ROOTVERSION}/src
+    rm \$tarfile
 else
-  echo 1>&2 "ERROR: wget https://root.cern.ch/download/${tarfile} failed!" >&2
+    echo 1>&2 "ERROR: wget https://root.cern.ch/download/${tarfile} failed!" >&2
 fi
 
-for var in $(echo ${Configuration} | tr "," " " | tr -d '"')
+for var in $config
 do
-   mkdir -p $basedir/${ROOTVERSION}/$var
-   if [ -d "$basedir/${ROOTVERSION}/$var" ]; then
-      if [[ $var == *gcc* ]] ; then
-         if [[ $var == *cc7* ]] ; then
-            FLAVOR="cc7"
-         fi
-         if [[ $var == *centos7* ]] ; then
-            FLAVOR="centos7"
-         fi
-         if [[ $var == *slc6* ]] ; then
-            FLAVOR="slc6"
-         fi
-         COMPILER=${var%-opt*}    # get the part before "-opt"
-         COMPILER=${COMPILER##*-} # get the part after the last '-'
-         GCC_VERSION=${COMPILER:0:4}.${COMPILER:4:1}
-         tarfile="root_v${ROOTVERSION}.Linux-${FLAVOR}-x86_64-${GCC_VERSION}.tar.gz"
-         wget "https://root.cern.ch/download/${tarfile}" >null 2>&1
-      fi
-      if [[ $var == *mac* ]] ; then
-         MAC_VER=${var%-clang*}   # get the part before "-clang"
-         MAC_VER=${MAC_VER##*mac} # get the part after "mac"
-         MAC_VERSION=${MAC_VER:0:2}.${MAC_VER:2:2}
-         CLANG_VER=${var%-opt*}   # get the part before "-opt"
-         CLANG_VER=${CLANG_VER##*-} # get the part after the last '-'
-         tarfile="root_v${ROOTVERSION}.macosx64-${MAC_VERSION}-${CLANG_VER}.tar.gz"
-         wget "https://root.cern.ch/download/${tarfile}" >null 2>&1
-      fi
-      if [ -f ${tarfile} ]; then
-         tar -zxf ${tarfile} -C $basedir/${ROOTVERSION}/$var
-         rm ${tarfile}
-      else
-         echo 1>&2 "ERROR: wget https://root.cern.ch/download/${tarfile} failed!" >&2
-      fi
-   fi
+    
+    mkdir -p $basedir/${ROOTVERSION}/\$var
+    
+    if [ -d $basedir/${ROOTVERSION}/\$var ]; then
+	if [[ "\$var" == *gcc* ]]; then
+            if [[ "\$var" == *cc7* ]]; then
+		FLAVOR="cc7"
+            fi
+            if [[ "\$var" == *centos7* ]]; then
+		FLAVOR="centos7"
+            fi
+            if [[ "\$var" == *slc6* ]]; then
+		FLAVOR="slc6"
+            fi
+            COMPILER=\${var%-opt*}    # get the part before "-opt"
+            COMPILER=\${COMPILER##*-} # get the part after the last '-'
+            GCC_VERSION=\${COMPILER:0:4}.\${COMPILER:4:1}
+            tarfile="root_v${ROOTVERSION}.Linux-\$FLAVOR-x86_64-\$GCC_VERSION.tar.gz"
+            wget https://root.cern.ch/download/\${tarfile} 
+            
+	fi
+	if [[ "\$var" == *mac* ]]; then
+            MAC_VER=\${var%-clang*}   # get the part before "-clang"
+            MAC_VER=\${MAC_VER##*mac} # get the part after "mac"
+            MAC_VERSION=\${MAC_VER:0:2}.\${MAC_VER:2:2}
+            CLANG_VER=\${var%-opt*}   # get the part before "-opt"
+            CLANG_VER=\${CLANG_VER##*-} # get the part after the last '-'
+            tarfile="root_v${ROOTVERSION}.macosx64-\$MAC_VERSION-\$CLANG_VER.tar.gz"
+            wget https://root.cern.ch/download/\${tarfile} >null 2>&1
+	fi
+	if [ -f \$tarfile ]; then
+            tar -zvxf \$tarfile -C $basedir/${ROOTVERSION}/\$var
+            rm \$tarfile
+	else
+            echo 1>&2 "ERROR: wget https://root.cern.ch/download/\${tarfile} failed!" >&2
+	fi
+    fi
 done
 echo "We are done"
 # Let's going to publish it
