bug fix

diff --git a/jenkins/root-cvmfs-release b/jenkins/root-cvmfs-release
--- a/jenkins/root-cvmfs-release
+++ b/jenkins/root-cvmfs-release
@@ -10,6 +10,8 @@ set -e -x
 
 # Let's create the directory first in CVMFS
 
+basedir=/cvmfs/sft.cern.ch/lcg/app/releases/ROOT/${ROOTVERSION} 
+
 sudo -i -u cvsft<<EOF
 
 # Let's open a transaction unless there is something else already opened
@@ -20,59 +22,59 @@ exit 1
 fi
 
 # Let's make the directory for new ROOT version first:
-echo "ROOT VERSION: \$ROOTVERSION"
-basedir=/cvmfs/sft.cern.ch/lcg/app/releases/ROOT/\${ROOTVERSION}
-echo "Value of the basedir: \$basedir"
-mkdir -p \$basedir
+echo "ROOT VERSION: $ROOTVERSION"
+echo "Value of the basedir: $basedir"
+mkdir -p $basedir
 
-if [ ! -d \$basedir ]; then
-  echo 1>&2 "The directory \$basedir doesn't exist!" >&2
+if [ ! -d $basedir ]; then
+  echo 1>&2 "The directory $basedir doesn't exist!" >&2
   exit 127
 fi
-mkdir -p \$basedir/\${ROOTVERSION}/src
-tarfile="root_v\${ROOTVERSION}.source.tar.gz"
-wget "https://root.cern.ch/download/\${tarfile}" >null 2>&1
-if [ -f \${tarfile} ]; then
-   tar -zxvf \${tarfile} -C \$basedir/\${ROOTVERSION}/src
-   rm \${tarfile}
+
+mkdir -p $basedir/${ROOTVERSION}/src
+tarfile="root_v${ROOTVERSION}.source.tar.gz"
+wget "https://root.cern.ch/download/${tarfile}" >null 2>&1
+if [ -f ${tarfile} ]; then
+   tar -zxvf ${tarfile} -C $basedir/${ROOTVERSION}/src
+   rm ${tarfile}
 else
-  echo 1>&2 "ERROR: wget https://root.cern.ch/download/\${tarfile} failed!" >&2
+  echo 1>&2 "ERROR: wget https://root.cern.ch/download/${tarfile} failed!" >&2
 fi
 
-for var in $(echo \${Configuration} | tr "," " " | tr -d '"')
+for var in $(echo ${Configuration} | tr "," " " | tr -d '"')
 do
-   mkdir -p \$basedir/\${ROOTVERSION}/\$var
-   if [ -d "\$basedir/\${ROOTVERSION}/\$var" ]; then
-      if [[ \$var == *gcc* ]] ; then
-         if [[ \$var == *cc7* ]] ; then
+   mkdir -p $basedir/${ROOTVERSION}/$var
+   if [ -d "$basedir/${ROOTVERSION}/$var" ]; then
+      if [[ $var == *gcc* ]] ; then
+         if [[ $var == *cc7* ]] ; then
             FLAVOR="cc7"
          fi
-         if [[ \$var == *centos7* ]] ; then
+         if [[ $var == *centos7* ]] ; then
             FLAVOR="centos7"
          fi
-         if [[ \$var == *slc6* ]] ; then
+         if [[ $var == *slc6* ]] ; then
             FLAVOR="slc6"
          fi
-         COMPILER=\${var%-opt*}    # get the part before "-opt"
-         COMPILER=\${COMPILER##*-} # get the part after the last '-'
-         GCC_VERSION=\${COMPILER:0:4}.\${COMPILER:4:1}
-         tarfile="root_v\${ROOTVERSION}.Linux-\${FLAVOR}-x86_64-\${GCC_VERSION}.tar.gz"
-         wget "https://root.cern.ch/download/\${tarfile}" >null 2>&1
+         COMPILER=${var%-opt*}    # get the part before "-opt"
+         COMPILER=${COMPILER##*-} # get the part after the last '-'
+         GCC_VERSION=${COMPILER:0:4}.${COMPILER:4:1}
+         tarfile="root_v${ROOTVERSION}.Linux-${FLAVOR}-x86_64-${GCC_VERSION}.tar.gz"
+         wget "https://root.cern.ch/download/${tarfile}" >null 2>&1
       fi
-      if [[ \$var == *mac* ]] ; then
-         MAC_VER=\${var%-clang*}   # get the part before "-clang"
-         MAC_VER=\${MAC_VER##*mac} # get the part after "mac"
-         MAC_VERSION=\${MAC_VER:0:2}.\${MAC_VER:2:2}
-         CLANG_VER=\${var%-opt*}   # get the part before "-opt"
-         CLANG_VER=\${CLANG_VER##*-} # get the part after the last '-'
-         tarfile="root_v\${ROOTVERSION}.macosx64-\${MAC_VERSION}-\${CLANG_VER}.tar.gz"
-         wget "https://root.cern.ch/download/\${tarfile}" >null 2>&1
+      if [[ $var == *mac* ]] ; then
+         MAC_VER=${var%-clang*}   # get the part before "-clang"
+         MAC_VER=${MAC_VER##*mac} # get the part after "mac"
+         MAC_VERSION=${MAC_VER:0:2}.${MAC_VER:2:2}
+         CLANG_VER=${var%-opt*}   # get the part before "-opt"
+         CLANG_VER=${CLANG_VER##*-} # get the part after the last '-'
+         tarfile="root_v${ROOTVERSION}.macosx64-${MAC_VERSION}-${CLANG_VER}.tar.gz"
+         wget "https://root.cern.ch/download/${tarfile}" >null 2>&1
       fi
-      if [ -f \${tarfile} ]; then
-         tar -zxf \${tarfile} -C \$basedir/\${ROOTVERSION}/\$var
-         rm \${tarfile}
+      if [ -f ${tarfile} ]; then
+         tar -zxf ${tarfile} -C $basedir/${ROOTVERSION}/$var
+         rm ${tarfile}
       else
-         echo 1>&2 "ERROR: wget https://root.cern.ch/download/\${tarfile} failed!" >&2
+         echo 1>&2 "ERROR: wget https://root.cern.ch/download/${tarfile} failed!" >&2
       fi
    fi
 done
